version: '2'

networks:
  sms-network:
    driver: bridge

services:
  ui-app :
    container_name: ui-app
    image: ${DOCKER_ID}pixelkube-ui
    build:
      context: src/pixelKube/
      dockerfile : Dockerfile
    ports:
      - 3000:80
    environment:
      - SMS_API_BASE_ENDPOINT=api-app:3002
    networks:
      - sms-network
  api-app:
    container_name: api-app
    image: ${DOCKER_ID}pixelkube-sms-api
    build:
      context: src/sms-spacemgmt-ms/
      dockerfile : Dockerfile
    ports:
      - 3001:80
    environment:
      - conectionstring=Host=sms-db:5432; Database=${POSTGRES_DB}; Username=postgres;Password=${POSTGRES_PASSWORD}
    networks:
      - sms-network
  cal-api-app:
    container_name: cal-api-app
    image: ${DOCKER_ID}pixelkube-cal-api
    build:
      context: src/CalendarService/
      dockerfile : Dockerfile_Api
    ports:
      - 3002:80
    environment:
      - conectionstring=Host=sms-db:5432; Database=${POSTGRES_DB}; Username=postgres;Password=${POSTGRES_PASSWORD}
    networks:
      - sms-network
  cal-background-app:
    container_name: cal-background-app
    image: ${DOCKER_ID}pixelkube-cal-background
    build:
      context: src/CalendarService/
      dockerfile : Dockerfile_Background
    ports:
      - 3003:80
    environment:
      - conectionstring=Host=sms-db:5432; Database=${POSTGRES_DB}; Username=postgres;Password=${POSTGRES_PASSWORD}
    networks:
      - sms-network
  sms-db:
    container_name: sms-db
    image: "${DOCKER_ID}pixelkube-sms-db"
    build:
      context: src/sms-spacemgmt-ms/docker-database/
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=pixelkube 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - sms-pgdata:${PGDATA}
    networks:
      - sms-network
  identity:
    container_name: keycloak-server
    image: "${DOCKER_ID}pixelkube-keycloak-server"
    build :
      context: identity-server/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - DB_VENDOR=POSTGRES
      - KC_DB=postgres
      - KC_DB_URL_HOST=sms-db
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_SCHEMA=public
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_DB_URL_PORT=5432
      - KC_HOSTNAME=demo.pixelkube.io
    networks:
      - sms-network
    depends_on:
      - sms-db
      
volumes:
  sms-pgdata:
  